### ISSUE TITLE
Model prediction errors

### ISSUE THREAD

**Issue by ejolly** [cosanlab/py-feat#119]
@TiankangXie 

- DRML give 0s for AU predictions of known smiling face
- SVM models give binary predictions only
- RF models give weird predictions 
- Logistic model disagrees with other non DNNs

See notebook [here](https://nbviewer.org/urls/dl.dropbox.com/s/gzk3u97z0y7fro4/dev.ipynb)

**Comment by ejolly** [comment]
Also our AU visualization model seems to only be compatible with `rf`, `svm`, and `logistic` AU models. DRML and JAANET don't have the correct number of AUs

**Comment by Feng-Chun** [comment]
@ejolly

**Comment by Feng-Chun** [comment]
@ejolly 

Hello Eshin,
 
I think that the AU visualization model is also not compatible with `rf` , `svm`, `logistic` AU models because the AUs in these models are not the same as AUs in the AU visualization model. 

AUs in AU models: 1, 2, 4, 5, 6, 7, 9, 10, `11`, 12, 14, 15, 17, 20, 23, 24, 25, 26, 28, 43. 
AUs in AU visualization model: 1, 2, 4, 5, 6, 7, 9, 10, 12, 14, 15, 17, `18`, 20, 23, 24, 25, 26, 28, 43.

Please let me know if I misunderstood anything. thanks!

**Comment by ejolly** [comment]
Thanks @Feng-Chun! We're in the process of revamping the visualization model so stay tuned for some updates soon!
