### ISSUE TITLE
Missing frames in detect_video results

### ISSUE THREAD

**Issue by Ben-FCC** [cosanlab/py-feat#129]
Hi there, 

I used detect_video to process my videos, but I got weird results. 
I don't know how it happens. 
The arguments I used are `skip_frames=1,batch_size = 256, singleframe4error = True`
 
A series of frames were missed in the results. (frame: 27391 -> 27517)
![截圖 2022-07-03 下午1 51 30](https://user-images.githubusercontent.com/65886339/177027466-3c73758c-14a1-40d5-974f-4d3d3cff0fc0.png)

Here are the warning messages when I was processing the videos.
![截圖 2022-07-03 下午1 51 48](https://user-images.githubusercontent.com/65886339/177027295-4e370cf9-5bc8-4a34-8cdf-c1d3182c223c.png)

Please let me know if I misunderstand anything.
Thanks!

**Comment by ljchang** [comment]
Hi @Ben-FCC , apologies for the issues you are having. We are currently in the process of updating both how batch processing is being done and error handling, which I believe will address this issue. WIP PR https://github.com/cosanlab/py-feat/pull/133.  The batch processing system that is currently implement has a lot of hacky ways to try and salvage as much data as possible when it encounters errors, rather than losing an entire batch of data. The `singleframe4error` flag is one example.

**Comment by ejolly** [comment]
Fixed in 0.5.0
