### ISSUE TITLE
Error: Expected a non-empty list of Tensors

### ISSUE THREAD

**Issue by med-tim** [cosanlab/py-feat#158]
I am passing in a list of images to be processed with detect_image and every time I get to the 530th image, this error gets thrown. There are no issues with images up until then. All images are the same exact size and the 10 images prior to the 530th are nearly the exact same.

Error:    
dfs.append(detector.detect_image(fpath, threshold = 0.985))
  File "/feat/detector.py", line 750, in detect_image
    raise ValueError(
ValueError: when using a batch_size > 1 all images must have the same dimensions or output_size must not be None so py-feat can rescale images to output_size. See pytorch error: 
torch.cat(): expected a non-empty list of Tensors

I am confused at this error because I am only using a batch_size=1.

**This is my code:**

detector = Detector(
    face_model="retinaface",
    landmark_model="mobilefacenet",
    au_model='xgb',
    emotion_model="resmasknet",
    facepose_model="img2pose",
)

images_path = ''
frames = [z for z in os.listdir(images_path) if 'pain' in z]
total_process = []
for frame in frames:
    frame_path = images_path+frame+'/'
    files = os.listdir(frame_path)
    for f in files:
        total_process.append(frame_path + f)
        
dfs = []
for fpath in tqdm(total_process,position = 0, leave = True):
    dfs.append(detector.detect_image(fpath, threshold = 0.985))
res = pd.concat(dfs)

**Comment by med-tim** [comment]
As an update, I have tested this on multiple different images and I keep getting this error:

  File "feat/detector.py", line 712, in detect_image
    landmarks = self.detect_landmarks(
  File feat/detector.py", line 426, in detect_landmarks
    extracted_faces, new_bbox = extract_face_from_bbox(
  File "feat/utils/image_operations.py", line 192, in extract_face_from_bbox
    faces = torch.cat(
RuntimeError: torch.cat(): expected a non-empty list of Tensors

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "myFile.py", line 23, in <module>
    dfs.append(detector.detect_image(fpath, threshold = 0.985, skip_failed_detections=True))
  File "feat/detector.py", line 750, in detect_image
    raise ValueError(
ValueError: when using a batch_size > 1 all images must have the same dimensions or output_size must not be None so py-feat can rescale images to output_size. See pytorch error: 
torch.cat(): expected a non-empty list of Tensors

**Comment by ljchang** [comment]
hi @med-tim, can you send a couple of images for us to recreate and debug including your problematic one (i.e., 530?). You can post a link here to download them if you feel comfortable, otherwise please send to my email luke.j.chang@dartmouth.edu.  I have a couple of ideas of where this bug could be, but will be able to figure it out much faster if I can recreate your issue.  Thanks!

**Comment by ljchang** [comment]
hi @med-tim thanks for letting us know about the HIPAA restrictions to sharing your images.

I've been able to recreate your issue when no faces are detected in a single image. This is for images with no faces and faces that are unable to be detected because they are rotated too much. For now, I would recommend skipping this images.  py-feat should definitely not be failing when this happens, we will try to fix this issue right away. Thanks so much for bringing this to our attention.

@ejolly @TiankangXie, I will try to submit a fix for this and will include it in the video_fix PR #157. Can you make sure we do a quick code review this week as this is a very embarrassing bug and we also need to add an image that does not have a face in it to our test suite so that we never encounter this one again.

**Comment by ljchang** [comment]
@med-tim: one quick other thing you could try to salvage a few images if you have a lot that are failing is to set a lower threshold for the face detection

**Comment by med-tim** [comment]
Great thanks for this information. By switching to the img2pose, I was able to iterate through another batch of images without issue but ran into issues when the face was rotated horizontally more than ~50%. Will try and skip those images for now.

I attempted another work around by trying to filter out images without a face detected by using: 

faces = RetinaFace.detect_faces(read_image)
if faces is not None:
            dfs.append(detector.detect_image(fpath, threshold=.3, skip_failed_detections=True))

While this prevented myself from passing images with no faces detected into detect_image(), I got this new error:

"An error occurred trying to merge detections into a single Fex object, as each type of detector is detecting a different number of faces:

face_detector: 3
pose_detector: 1
landmark_detector: 3
au_detector: 3
emotion_detector: 3"

There is not currently a way to run detect_image() while excluding pose_detector, correct?
