### ISSUE TITLE
from feat.utils import read_pictures have a mistake

### ISSUE THREAD

**Issue by Zhangqian110** [cosanlab/py-feat#162]
Hello,
I want to run :
from feat import Detector
from feat.utils import read_pictures
frame = read_pictures(['my_image.jpg'])
detector = Detector()
detector.detect_aus(frame)

But when I use "from feat.utils import read_pictures" I will get "cannot import name 'read_pictures' from 'feat.utils'.", and I can't find read_pictures in feat.utils.
How can I solve this problem?
Thanks very much.

**Comment by shahzain110** [comment]
any solutions?

**Comment by RemiSahl** [comment]
Looks that this function was removed when the utils module was refactored.
You can find a reference to it in 0.4.0 version here if you want to re-use this code: https://github.com/cosanlab/py-feat/blob/0.4.0/feat/utils.py#L907

The confusion probably comes from this example in the detect_faces function:
https://github.com/cosanlab/py-feat/blob/0.4.0/feat/detector.py#L324

**Comment by ejolly** [comment]
Sorry for the confusion @shahzain110 and thanks for the solution @RemiSahl!

We now recommend using:

`from torchvision.io import read_image` if you want to process a frame directly. We highly recommend using `.detect_image` instead of `.detect_faces` as we handle rescaling, padding, and images with different alpha channels using our `ImageDataset` for you.
